/**
 * leads.js
 * Lead capture form — shown before the quote modal.
 * Collects customer details, then passes them into the quote.
 */

// ─── CONFIG ────────────────────────────────────────────────────────────────────

// Change this to the email address that should receive enquiries
const ENQUIRY_EMAIL = 'enquiries@yourcompany.co.uk';

// ─── STATE ─────────────────────────────────────────────────────────────────────

// Populated when the lead form is submitted
const leadInfo = {
  name:  '',
  email: '',
  phone: '',
  notes: '',
};

// ─── LEAD MODAL OPEN / CLOSE ───────────────────────────────────────────────────

function openLeadModal() {
  document.getElementById('leadModal').classList.add('open');
  document.getElementById('leadName').focus();
}

function closeLeadModal() {
  document.getElementById('leadModal').classList.remove('open');
}

// ─── FORM SUBMISSION ───────────────────────────────────────────────────────────

function submitLeadForm() {
  const name  = document.getElementById('leadName').value.trim();
  const email = document.getElementById('leadEmail').value.trim();

  // Basic validation
  if (!name) {
    showLeadError('Please enter your name.');
    document.getElementById('leadName').focus();
    return;
  }
  if (!email || !email.includes('@')) {
    showLeadError('Please enter a valid email address.');
    document.getElementById('leadEmail').focus();
    return;
  }

  // Store details
  leadInfo.name  = name;
  leadInfo.email = email;
  leadInfo.phone = document.getElementById('leadPhone').value.trim();
  leadInfo.notes = document.getElementById('leadNotes').value.trim();

  clearLeadError();
  closeLeadModal();
  openQuoteModal(); // defined in quote.js
}

function skipLeadForm() {
  leadInfo.name  = '';
  leadInfo.email = '';
  leadInfo.phone = '';
  leadInfo.notes = '';
  clearLeadError();
  closeLeadModal();
  openQuoteModal();
}

function showLeadError(msg) {
  const el = document.getElementById('leadError');
  el.textContent = msg;
  el.style.display = 'block';
}

function clearLeadError() {
  const el = document.getElementById('leadError');
  el.textContent = '';
  el.style.display = 'none';
}

// Allow Enter key to submit from any field except the notes textarea
document.addEventListener('keydown', e => {
  if (e.key !== 'Enter') return;
  if (!document.getElementById('leadModal').classList.contains('open')) return;
  if (document.activeElement.id === 'leadNotes') return;
  submitLeadForm();
});

// ─── ENQUIRY EMAIL BUILDER ─────────────────────────────────────────────────────

/**
 * Opens the user's mail client with a pre-filled enquiry containing
 * the customer's details and a plain-text quote summary.
 */
function sendEnquiryEmail() {
  const total = calcTotal(state);

  const specs = [
    `Width:       ${state.width}m`,
    `Depth:       ${state.depth}m`,
    `Height:      ${state.height}m`,
    `Floor Area:  ${(state.width * state.depth).toFixed(1)}m²`,
    `Foundation:  ${FOUNDATION_LABELS[state.foundation] ?? state.foundation}`,
    `Roof Style:  ${ROOF_STYLE_LABELS[state.roof] ?? state.roof}`,
    `Roof Finish: ${ROOF_FINISH_LABELS[state.roofFinish] ?? state.roofFinish}`,
    `Cladding:    ${CLADDING_LABELS[state.cladding] ?? state.cladding}`,
    `Doors:       ${state.openings.filter(o=>o.type==='door').map(o=>DOOR_LABELS[o.style]??o.style).join(', ')||'None'}`,
    `Windows:     ${state.openings.filter(o=>o.type==='window').map(o=>WINDOW_STYLE_LABELS[o.style]??o.style).join(', ')||'None'}`,
  ].join('\n');

  const extras = Object.entries(state.extras)
    .filter(([, on]) => on)
    .map(([k]) => k)
    .join(', ') || 'None';

  const counted = [
    state.ethernetPoints > 0 && `CAT6 Ethernet: ${state.ethernetPoints} points`,
    state.internalLights  > 0 && `Internal lights: ${state.internalLights}`,
    state.externalLights  > 0 && `External lights: ${state.externalLights}`,
    state.extras.decking  && `Decking: ${state.deckingArea}m²`,
  ].filter(Boolean).join('\n') || 'None';

  const customerBlock = leadInfo.name
    ? `CUSTOMER DETAILS\n----------------\nName:  ${leadInfo.name}\nEmail: ${leadInfo.email}${leadInfo.phone ? '\nPhone: ' + leadInfo.phone : ''}${leadInfo.notes ? '\nNotes: ' + leadInfo.notes : ''}\n\n`
    : '';

  const body = [
    customerBlock,
    'CONFIGURATION\n-------------',
    specs,
    '',
    'EXTRAS & ADD-ONS',
    '----------------',
    'Toggles: ' + extras,
    counted,
    '',
    'ESTIMATE TOTAL (exc. VAT)',
    '-------------------------',
    `£${Math.round(total).toLocaleString('en-GB')}`,
    '',
    '---',
    'Generated by Garden Room Configurator',
  ].join('\n');

  const subject = encodeURIComponent(
    `Garden Room Enquiry${leadInfo.name ? ' — ' + leadInfo.name : ''}`
  );

  window.location.href = `mailto:${ENQUIRY_EMAIL}?subject=${subject}&body=${encodeURIComponent(body)}`;
}
